import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";

const fontBarlow = Barlow_Condensed({
  weight: ["400", "700"],
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fazfood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontBarlow.variable} antialiased`}>
        <TanstackQueryProvider>
          <Toaster position="top-center" />
          <MainLayout>
            {children}
          </MainLayout>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
